# Generated by Django 4.1.1 on 2023-10-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginid', models.CharField(max_length=100, unique=True)),
                ('imageName', models.CharField(max_length=100)),
                ('xorShiftKey', models.CharField(max_length=100, unique=True)),
                ('byteKey', models.IntegerField()),
                ('cdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'EncryptionTable',
            },
        ),
    ]
