# Generated by Django 4.2.11 on 2024-05-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_encryptionmodels_loginid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageSharingModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imgId", models.CharField(max_length=100)),
                ("sharefrom", models.CharField(max_length=100)),
                ("imageName", models.CharField(max_length=100)),
                ("xorShiftKey", models.IntegerField()),
                ("byteKey", models.IntegerField()),
                ("recipientUser", models.CharField(max_length=100)),
                ("cdate", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ImageSharingTable",
            },
        ),
    ]
